on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        run:  echo "hello world"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: version python
        run:  python --version 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install python for github
        run: |
          pip install PyGithub 
      - name: Install python for terraform
        run: |
          pip3 install --user pyterprise
      - name: Install python cloud client for terraform
        run: |
          pip install terraform-cloud-client
      - name: Install python cloud client for terraform
        run: |
          pip install tfc-client
      - name: run python1
        run: |
          python ./main.py
      
          
        
    
