on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup python
        run:  echo "hello world"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: version python
        run:  python --version
      - name: run python
        run: |
          python ./main.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install pyhon for github
        run: |
          pip install PyGithub
        
    
